#!/bin/sh

### #####################################################################
## Load environment from file
#

DAPEI=/tmp/dapei

source ${DAPEI}

### #####################################################################
## Call the real application 
#
EXE=`basename $0 | awk -F'dabao__' '{ print $2 }'`

da_BASEDIR=/usr/local/bin
exec ${da_BASEDIR}/${EXE} $@

