#!/bin/sh

NMENV=/tmp/nm.env
pushenv () {
    echo "export $1" >> ${NMENV}
}

echo -n "" > ${NMENV}

# Dump boot command line
echo
echo "DUMP /proc/cmdline. >>>>>"
cat /proc/cmdline
echo "<<<<<"

grep "\bkl2syslog\b" -w -o /proc/cmdline
if [ "$?" == "0" ]; then
    pushenv KLOG_TO_SYSLOG=YES
fi

# Remote Default klog configure
KLOG_RMCFG=`grep "\bklcfg=.*" -o /proc/cmdline | cut -d ' ' -f1 | awk -F= '{ print $2 }'`
if [ "$KLOG_RMCFG" != "" ]; then
    wget "${KLOG_RMCFG}" -O /tmp/klog.df.cfg
    cat /tmp/klog.df.cfg

    # KLOG_DFCFG will internal used by klog_init
    pushenv KLOG_DFCFG=/tmp/klog.df.cfg
fi

# KLOG Save to remote
KLOG_SEWER_REMOTE=`grep "\bkl2remote=.*" -o /proc/cmdline | cut -d ' ' -f1 | awk -F= '{ print $2 }'`
if [ "$KLOG_SEWER_REMOTE" != "" ]; then
    pushenv KLOG_SEWER_REMOTE=${KLOG_SEWER_REMOTE}
fi

# KLOG Save to file
KLOG_SEWER_LOCAL=`grep "\bkl2local=.*" -o /proc/cmdline | cut -d ' ' -f1 | awk -F= '{ print $2 }'`
if [ "$KLOG_SEWER_LOCAL" != "" ]; then
    pushenv KLOG_SEWER_LOCAL=${KLOG_SEWER_LOCAL}
fi

# KLOG_RTCFG will used by nh_klog
pushenv KLOG_RTCFG=/tmp/klog.rt.cfg

# KLOG Agent is a opt-rpc-server
/bin/klagent.sh ${KLOG_RTCFG} &

# PCD output 
PCDOUT=`grep "\bpcdout=.*" -o /proc/cmdline | cut -d ' ' -f1 | awk -F= '{ print $2 }'`
if [ "$PCDOUT" != "" ]; then
    pushenv PCDOUT=${PCDOUT}
else
    pushenv PCDOUT=/dev/null
fi

# HOOK
# preload=/lib/libnemohook.so
PRELOAD=`grep "\bpreload=.*" -o /proc/cmdline | cut -d ' ' -f1 | awk -F= '{ print $2 }'`
if [ "$PRELOAD" != "" ]; then
    pushenv LD_PRELOAD=${PRELOAD}
fi

pushenv NH_SYSLOG_NOREAL=YES

echo
echo ">>>>>>>> DUMP ${NMENV} >>>>>>>>"
cat ${NMENV}
echo "<<<<<<<< DUMP DONE <<<<<<<<"
echo

# Give user a chance to edit klog configure files
echo "Into new shell to edit ${NMENV}, Ctrl-D to quit and continue"
PS1="klog@(${NMENV})$ " sh

source ${NMENV}

echo "Will call REAL pcd"
/usr/sbin/pcd.real $@ -v &> ${PCDOUT} 

