export HI_PRJ_ROOT = ..
-include $(HI_PRJ_ROOT)/Makefile.defs

LOCAL_OUT_ELF = dalogsewer
LOCAL_OUT_OBJS = dalogsewer.o 

.PHONY: all clean

all: $(LOCAL_OUT_ELF) $(LOCAL_OUT_OBJS) 

-include $(HI_PRJ_ROOT)/Makefile.rules

