# Note: Automatically generated by kfg, do not edit.

export HI_PRJ_ROOT := $(CURDIR)
export HI_PLATFORM := '7231'
export HI_BUILD := 'all'


-include Makefile.defs
.PHONY: all clean install uninstall

#########################################################################
## daben
#
.PHONY: daben.all
all: daben.all
daben.all:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/daben all

.PHONY: daben.clean
clean: daben.clean
daben.clean:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/daben clean

.PHONY: daben.install
install: daben.install
daben.install:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/daben install

.PHONY: daben.uninstall
uninstall: daben.uninstall
daben.uninstall:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/daben uninstall

#########################################################################
## dadai
#
.PHONY: dadai.all
all: dadai.all
dadai.all:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dadai all

.PHONY: dadai.clean
clean: dadai.clean
dadai.clean:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dadai clean

.PHONY: dadai.install
install: dadai.install
dadai.install:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dadai install

.PHONY: dadai.uninstall
uninstall: dadai.uninstall
dadai.uninstall:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dadai uninstall

#########################################################################
## dagou
#
.PHONY: dagou.all
all: dagou.all
dagou.all:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dagou all

.PHONY: dagou.clean
clean: dagou.clean
dagou.clean:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dagou clean

.PHONY: dagou.install
install: dagou.install
dagou.install:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dagou install

.PHONY: dagou.uninstall
uninstall: dagou.uninstall
dagou.uninstall:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dagou uninstall

#########################################################################
## daxia
#
.PHONY: daxia.all
all: daxia.all
daxia.all:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/daxia all

.PHONY: daxia.clean
clean: daxia.clean
daxia.clean:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/daxia clean

.PHONY: daxia.install
install: daxia.install
daxia.install:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/daxia install

.PHONY: daxia.uninstall
uninstall: daxia.uninstall
daxia.uninstall:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/daxia uninstall

#########################################################################
## dr
#
.PHONY: dr.all
all: dr.all
dr.all:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dr all

.PHONY: dr.clean
clean: dr.clean
dr.clean:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dr clean

.PHONY: dr.install
install: dr.install
dr.install:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dr install

.PHONY: dr.uninstall
uninstall: dr.uninstall
dr.uninstall:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/dr uninstall

#########################################################################
## inotdo
#
.PHONY: inotdo.all
all: inotdo.all
inotdo.all:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/inotdo all

.PHONY: inotdo.clean
clean: inotdo.clean
inotdo.clean:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/inotdo clean

.PHONY: inotdo.install
install: inotdo.install
inotdo.install:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/inotdo install

.PHONY: inotdo.uninstall
uninstall: inotdo.uninstall
inotdo.uninstall:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/inotdo uninstall

#########################################################################
## muzei
#
.PHONY: muzei.all
all: muzei.all
muzei.all:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/muzei all

.PHONY: muzei.clean
clean: muzei.clean
muzei.clean:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/muzei clean

.PHONY: muzei.install
install: muzei.install
muzei.install:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/muzei install

.PHONY: muzei.uninstall
uninstall: muzei.uninstall
muzei.uninstall:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/muzei uninstall

#########################################################################
## netmon
#
.PHONY: netmon.all
all: netmon.all
netmon.all:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/netmon all

.PHONY: netmon.clean
clean: netmon.clean
netmon.clean:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/netmon clean

.PHONY: netmon.install
install: netmon.install
netmon.install:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/netmon install

.PHONY: netmon.uninstall
uninstall: netmon.uninstall
netmon.uninstall:
	make -C /media/auv/Windows8_OS/Users/nemo/work/bigkillmachine/SRCS/netmon uninstall

