export BKM_PRJ_ROOT = ../..
-include $(BKM_PRJ_ROOT)/Makefile.defs

LOCAL_OUT_ELF = ldmon
LOCAL_OUT_OBJS = ldmon.o

.PHONY: all clean

all: $(LOCAL_OUT_ELF) $(LOCAL_OUT_OBJS) 

-include $(BKM_PRJ_ROOT)/Makefile.rules

