export BKM_PRJ_ROOT = ../..
-include $(BKM_PRJ_ROOT)/Makefile.defs

LOCAL_OUT_ELF = inotdo
LOCAL_OUT_OBJS = inotdo.o 

.PHONY: all clean

all: $(LOCAL_OUT_ELF) $(LOCAL_OUT_OBJS) 

-include $(BKM_PRJ_ROOT)/Makefile.rules

