 * ============================================================================
 */

/**
 * @file     timemgr.h
 * @author   Lianghe Li
 * @date     Feb 15, 2011
 */
#ifndef __TIMEMGR_H_
#define __TIMEMGR_H_

/**
 * @brief Time manager public definitions
 * @defgroup TIMEMGR Time manager public definitions
 * The public definitions. This API os shared by the Time Manager and the Time Proxy
 *
 * @{
 */

/**** Includes ***************************************************************/
#include <glib.h>

/**** Definitions ************************************************************/
#define TIMEMGR_PATH                   "/com/nemotv/timemgr"
#define TIMEMGR_INTERFACE              "com.nemotv.timemgr"
// #define TIMEMGR_ADDRESS                "unix:abstract=/tmp/timemgr"
#define TIMEMGR_ADDRESS                "unix:path=/var/run/dbus/timemgr"

#define APP_TIME_SOURCE_PATH           "/com/nemotv/AppTimeSource"
#define APP_TIME_SOURCE_INTERFACE      "com.nemotv.AppTimeSource"
// #define APP_TIME_SOURCE_ADDRESS        "unix:abstract=/tmp/AppTimeSource"
#define APP_TIME_SOURCE_ADDRESS        "unix:path=/var/run/dbus/AppTimeSource"

/**
 * Events generated by the time manager.
 */
typedef enum
{
    TIMEMGR_EVENT_TIME_CHANGED,         /*!< Time changed due to new data in time source */
    TIMEMGR_EVENT_TIME_ZONE_CHANGED,    /*!< Time zone has been changed (by user)        */
    TIMEMGR_EVENT_DAYLIGHT_SAVINGS_ON,  /*!< Daylight savings is now applied             */
    TIMEMGR_EVENT_DAYLIGHT_SAVINGS_OFF, /*!< Daylight savings has been turned off        */
    TIMEMGR_EVENT_ENDDEF                /* Terminator                                    */
}   timemgr_event_t;

#define SIGNAL_NAME_TIME_CHANGED            "time_changed"
#define SIGNAL_NAME_TIME_ZONE_CHANGED       "time_zone_changed"
#define SIGNAL_NAME_DAYLIGHT_SAVINGS_ON     "daylight_savings_on"
#define SIGNAL_NAME_DAYLIGHT_SAVINGS_OFF    "daylight_savings_off"

#endif /* __TIMEMGR_H_ */

