#!/bin/sh

#
# init will give a chance to modify the BKM env
#

### #####################################################################
## Print welcome
#
echo ">>>> INTO DA-INIT, uptime is `uptime`"
cat /etc/banner.bkm

### #####################################################################
## Collect envionment for dalogsewer and ntvapps
#
da_ENVFILE=/tmp/dalogsewer.env
#da_ENVFILE=./myenv

initenv() {
    echo -n "" > ${da_ENVFILE}
    echo '# export LOGSEW_PORT=50000' >> ${da_ENVFILE}
    echo '# export LOGSEW_FILE=/tmp/dalog.sew' >> ${da_ENVFILE}
    echo '' >> ${da_ENVFILE}
}

if [ ! -e ${da_ENVFILE} ]; then
    initenv
fi

PS1="BKM> " /bin/sh

source ${da_ENVFILE}
/bin/dalogsewer &

### #####################################################################
## Run the real init
#
rm -f /tmp/init
ln -s /sbin/init.otvorig /tmp/init

echo ">>>> WILL CALL REAL INIT, uptime is `uptime`"
exec /tmp/init

