#!/bin/sh

### #####################################################################
## Load environment from file
#

da_ENVFILE=/home/env.da

source ${da_ENVFILE}

### #####################################################################
## Call the real application 
#
EXE=`basename $0`

da_BASEDIR=/usr/local/bin

if [ $EXE == 'muzei' ]; then
    EXE=$1
    shift
    exec $EXE $@
else
    exec ${da_BASEDIR}/`basename $0`.otvorig $@
fi

