#!/bin/sh

### #####################################################################
## Load environment from file
#

da_ENVFILE=./myenv
#da_ENVFILE=./myenv
#da_ENVFILE=./myenv

source ${da_ENVFILE}

### #####################################################################
## Call the real application 
#
EXE=`basename $0`

da_BASEDIR=.
#da_BASEDIR=/tmp
#da_BASEDIR=/home/ntvroot

if [ $EXE == 'muzei' ]; then
    EXE=$1
    shift
    exec $EXE $@
else
    exec ${da_BASEDIR}/`basename $0`.otvorig $@
fi

