#!/bin/sh

#
# init will give a chance to modify the BKM env
#

echo ">>>> INTO DA-INIT, uptime is `uptime`"
cat banner

# Copy BKM file to /tmp

PS1="BKM> " /bin/sh

echo ">>>> WILL CALL REAL INIT, uptime is `uptime`"
exec /sbin/init.daorg

