#!/bin/sh

#
# init will give a chance to modify the BKM env
#

busybox ">>>> INTO DA-INIT, uptime is `uptime`"
busybox cat banner

# Copy BKM file to /tmp

PS1="BKM> " /bin/sh

busybox ">>>> WILL CALL REAL INIT, uptime is `uptime`"
exec /sbin/init.real

