#!/bin/sh

### #####################################################################
## Parse script name
#
SCRIPT=`basename $0`
CMD=`echo ${SCRIPT} | awk -F. ' { print $1 }' | xargs basename`
BLD=`echo ${SCRIPT} | awk -F. ' { print $2 }'`
CFG=`echo ${SCRIPT} | awk -F. ' { print $3 }'`

if [ "${CMD}" != "m" ]; then
    echo "Please ln -s /usr/local/bin/m m.<BLD_TYPE>.<CFG_TYPE>"
    exit
fi

### #####################################################################
## Append skmpost.sh to post_process.sh
#
grep "skmpost_placeHolder_83264" post_process.sh &> /dev/null
if [ $? ]; then
    echo "Already includes skmpost.sh"
else
    echo 'echo "skmpost_placeHolder_83264:" &> /dev/null; echo "$WORKING_DIR/skmpost.sh $BUILD_TYPE $CONFIG_TYPE $WORKING_DIR" >> $WORKING_DIR/ntv_customize_fs.txt' >> post_process.sh
fi

### #####################################################################
## Run the make command
#
source ../set_env_bash.sh
time make DEBUG_INIT=1 CONFIG_TYPE=${CFG} BUILD_TYPE=${BLD} MSUR_DEBUG=YES $1 $2 $3 $4 $5 $6 $7 $8 $9

