#!/bin/sh

# start udhcpc
cp /usr/share/udhcpc/default.script /tmp
sed -i 's/sbin/bin/g' /tmp/default.script
nohup udhcpc -s /tmp/default.script

# start telnetd
nohup telnetd

# Show me
ifconfig

# XXX: the chmod in m.xxx.yyy cannot work
chmod a+rwx /dev/console

