export NH_PRJ_ROOT = ..
-include $(NH_PRJ_ROOT)/Makefile.defs

LOCAL_OUT_ELF = klagent
LOCAL_OUT_OBJS = klog-agent.o

.PHONY: all clean

all: $(LOCAL_OUT_ELF) $(LOCAL_OUT_OBJS) 

-include $(NH_PRJ_ROOT)/Makefile.rules
